openapi: 3.0.3
info:
  title: Forem API V1 agent_sessions profile images API
  version: 1.0.0
  description: "Access Forem articles, users and other resources via API.\n        For a real-world example of Forem in action, check out [DEV](https://www.dev.to).\n        All endpoints can be accessed with the 'api-key' header and a accept header, but\n        some of them are accessible publicly without authentication.\n\n        Dates and date times, unless otherwise specified, must be in\n        the [RFC 3339](https://tools.ietf.org/html/rfc3339) format."
servers:
- url: https://dev.to/api
  description: Production server
security:
- api-key: []
tags:
- name: profile images
paths:
  /api/profile_images/{username}:
    get:
      summary: A Users or organizations profile image
      tags:
      - profile images
      description: "This endpoint allows the client to retrieve a user or organization profile image information by its\n        corresponding username."
      operationId: getProfileImage
      parameters:
      - name: username
        in: path
        required: true
        description: The parameter is the username of the user or the username of the organization.
        schema:
          type: string
        example: janedoe
      responses:
        '200':
          description: An object containing profile image details
          content:
            application/json:
              example:
                type_of: profile_image
                image_of: user
                profile_image: /uploads/user/profile_image/4234/0984d355-dddc-4f79-9950-1702fa47ee3e.jpeg
                profile_image_90: /uploads/user/profile_image/4234/0984d355-dddc-4f79-9950-1702fa47ee3e.jpeg
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ProfileImage'
        '404':
          description: Resource Not Found
          content:
            application/json:
              example:
                error: not found
                status: 404
  /profile_images/{username}:
    get:
      summary: A Users or organizations profile image
      tags:
      - profile images
      description: "This endpoint allows the client to retrieve a user or organization profile image information by its\n        corresponding username."
      operationId: getProfileImage
      parameters:
      - name: username
        in: path
        required: true
        description: The parameter is the username of the user or the username of the organization.
        schema:
          type: string
        example: janedoe
      responses:
        '200':
          description: An object containing profile image details
          content:
            application/json:
              example:
                type_of: profile_image
                image_of: user
                profile_image: /uploads/user/profile_image/1419/f2b13e85-a3a0-49cf-9da0-7922248be024.jpeg
                profile_image_90: /uploads/user/profile_image/1419/f2b13e85-a3a0-49cf-9da0-7922248be024.jpeg
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ProfileImage'
        '404':
          description: Resource Not Found
          content:
            application/json:
              example:
                error: not found
                status: 404
components:
  schemas:
    ProfileImage:
      description: A profile image object
      type: object
      properties:
        type_of:
          description: Return profile_image
          type: string
        image_of:
          description: Determines the type of the profile image owner (user or organization)
          type: string
        profile_image:
          description: Profile image (640x640)
          type: string
        profile_image_90:
          description: Profile image (90x90)
          type: string
  securitySchemes:
    api-key:
      type: apiKey
      name: api-key
      in: header
      description: "API Key authentication.\n\nAuthentication for some endpoints, like write operations on the\nArticles API require a DEV API key.\n\nAll authenticated endpoints are CORS disabled, the API key is intended for non-browser scripts.\n\n### Getting an API key\n\nTo obtain one, please follow these steps:\n\n  - visit https://dev.to/settings/extensions\n  - in the \"DEV API Keys\" section create a new key by adding a\n    description and clicking on \"Generate API Key\"\n\n    ![obtain a DEV API Key](https://user-images.githubusercontent.com/37842/172718105-bd93664e-76e0-477d-99c4-265dda0b06c5.png)\n\n  - You'll see the newly generated key in the same view\n    ![generated DEV API Key](https://user-images.githubusercontent.com/37842/172718151-e7fe26a0-9937-42e8-96c6-333acdab9e49.png)"
